Create user model
wolox-training/edc-express-js pull request #4
Opened 2018-08-16 19:31 UTC by EduardoContreras

**Summary**
Was added create user model into app and generated the same model to data base with sequelize orm.

**Trello Card**
https://trello.com/c/AOx5qsaA/27-modelo-de-usuario

2018-08-16 19:33 UTC, gonziesc requested changes
Delete your unused dependencies. Also, id call the table name `users`

2018-08-17 16:19 UTC, gonziesc approved these changes
its ok but wait to finish the kickoff changes

2018-08-21 11:50 UTC, EduardoContreras commented
@gonziesc waiting for approval kickoff branch for merge.

2018-08-21 16:46 UTC, gonziesc approved these changes

2018-08-21 16:46 UTC, gonziesc commented on package.json
> +    "sinon": "^6.1.5"
are you using all of this?

2018-08-21 17:35 UTC, EduardoContreras commented on package.json
> +    "sinon": "^6.1.5"
really no, but i will use in the next branch sign-up.

2018-08-24 11:49 UTC, merged