Sign up
wolox-training/edc-express-js pull request #5
Opened 2018-08-16 19:35 UTC by EduardoContreras

**Summary**

.- This Pull Request contains sign-up user on endpoint POST with all required validations of trello card and was merged with previous branches 'kickOff' and 'create-user-model'.

**Trello Card**
https://trello.com/c/GWo93nQs/2-sign-up

2018-08-21 16:48 UTC, gonziesc requested changes

2018-08-21 16:48 UTC, gonziesc commented on app/controllers/user.js
> +  Model.sequelize.sync().then(function() {
no need of this here

2018-08-21 16:48 UTC, gonziesc commented on app/controllers/user.js
> +  Model.sequelize.sync().then(function() {
same

2018-08-21 16:48 UTC, gonziesc commented on app/controllers/user.js
> +  Model.sequelize.sync().then(function() {
same

2018-08-21 16:48 UTC, gonziesc commented on app/controllers/user.js
> +  Model.sequelize.sync().then(function() {
same

2018-08-21 16:48 UTC, gonziesc commented on app/controllers/user.js
> +  Model = require('../models/index'),
you can import User

2018-08-21 16:48 UTC, gonziesc commented on app/models/user.js
> +          if (
validate this in the controller or a service, not in the database

2018-08-21 16:48 UTC, gonziesc commented on documentation.js
> +const dictum = require('dictum.js');
no need of this

2018-08-21 16:48 UTC, gonziesc commented on test/factories/user.js
> +const faker = require('faker'),
nice!

2018-08-24 11:55 UTC, EduardoContreras commented on app/models/user.js
> +          if (
But, the approach is oriented to DDD ( domain driver desing)... all validation are over the model. Its not valid? And the last point before save to db is in the model.

2019-01-02 12:42 UTC, closed without merging